# Generated by Django 4.2.4 on 2023-08-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoFun', '0002_alter_todolist_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
